Home Page and About Page
basnetlaxmi/first-capstone-project pull request #2
Opened 2021-09-16 17:55 UTC by basnetlaxmi

### In this milestone, I have :

- Created Global Hackathon Website
- Added home page and give style to it
- Added about page and give style to it
- Created 'Featured Speaker ' section dynamically with js
- Used bootstrap and media-query to make responsive
- Added hamburger menu

Here is my [video link](https://www.loom.com/share/284327174ecf47e89b3a73341dce1d9f) about the description of the project.

2021-09-16 19:55 UTC, Lameck1 requested changes
Hi @basnetlaxmi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Add the node-modules directory to .gitignore file.
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-16 19:55 UTC, Lameck1 commented on index.html
> +                                    <a class="nav-link active" aria-current="page" href="./pages/about.html">About</a>
- [ ] This link leads to no page in your project. This happens when the home page is open in mobile view and the user clicks on the About link in the mobile menu. Refactor it to:
```suggestion
<a class="nav-link active" aria-current="page" href="about.html">About</a>
```

2021-09-16 19:55 UTC, Lameck1 commented on README.md
> +- Microverse
- [ ] Credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), is missing in the Acknowledgements. Please add it as it is a requirement by the [Creative Commons License](https://creativecommons.org/licenses/).

2021-09-16 19:55 UTC, Lameck1 commented on README.md
> + [Link to My Portfolio](https://basnetlaxmi.github.io/my-portfolio/)
- [ ] The Live Demo link should be a link to the deployed version of this project, not the developer portfolio. Please deploy this project to GitHub pages and provide the live version link in this section of the README.

2021-09-16 19:55 UTC, Lameck1 commented on css/style.css
> +}
- [ ] The footer's background should be white on the Mobile version of the page and dark on the desktop version of the page. Look at the screenshot below to help you notice the differences and make necessary adjustments. Take care of the font colors too.

| The Provide Design |
| --- |
| ![footer-desktop-design](https://user-images.githubusercontent.com/45002654/133670516-d031cba3-60f2-4ab6-80cc-4a8dabdf53fd.PNG) |

| Your implementation |
| --- |
| ![footer-imp](https://user-images.githubusercontent.com/45002654/133670633-260919a4-1a20-47a0-999d-012691f8fe97.PNG) |

2021-09-16 19:55 UTC, Lameck1 commented on css/about.css
> +  }
- How about we do a little improvement in this section. The implementation and the design slightly don't match.

| The Provide Design |
| --- |
| ![partner-design](https://user-images.githubusercontent.com/45002654/133671844-274587b4-c26f-44f1-ab75-0802bec0d2d4.PNG) |

| Your implementation |
| --- |
| ![partner-imp](https://user-images.githubusercontent.com/45002654/133671905-cc126c16-e6f3-4942-82f1-03518374f6cb.PNG) |

## What to improve in this section
- The background-color
- Cente- align the Partner logos and reduce the margins between them.

2021-09-16 19:55 UTC, Lameck1 commented on css/style.css
> +.speaker-section .speakers .speaker-info {
- [ ] This speaker section looks very good. We only need to add margins/paddings to the left and to the right or reduce the width of the `div` with the class of `.speakers` and give a margin value of `margin: 0 auto` to center it within the page.

The here is that the implementation stretches the whole width of the page. Try and work on this.

| The Provide Design |
| --- |
| ![featured-design](https://user-images.githubusercontent.com/45002654/133673712-9602afd7-3ae2-4700-be39-5b04ce6c3a9c.PNG) |

| Your implementation |
| --- |
| ![featured-imp](https://user-images.githubusercontent.com/45002654/133673591-f56c172f-c0a9-428e-a8fa-91a767e1833e.PNG) |

2021-09-16 19:55 UTC, Lameck1 commented on about.html
> +      </section>
- [ ] This section's design for the mobile version of the about page is not in line with the provide design. Look at the differences in the screenshot below and make necessary adjustments.

| The Provide design | Your Implementation |
| --- | --- |
| ![past-gloabal-design](https://user-images.githubusercontent.com/45002654/133676492-2b146b9c-d83d-4ef1-bebb-554bdb160bee.PNG) | ![past-global-imp](https://user-images.githubusercontent.com/45002654/133676585-6583e327-10f9-4db8-8638-8c5e06bc7f37.PNG) |

- Text alignment for sections of the about page should be center in the mobile version.
- The two banners are not properly sized and position as in the provided design.

2021-09-17 12:02 UTC, george-shammar approved these changes
Hi @basnetlaxmi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-17 12:03 UTC, merged